version: '3'

services:
  api:
    build: .
    image: strapi/strapi
    container_name: healthdesk-api
    environment:
      - APP_NAME=healthdesk-api
      - DATABASE_CLIENT=mongo
      - DATABASE_HOST=db
      - DATABASE_PORT=27017
      - DATABASE_NAME=healthdesk-db
      - DATABASE_USERNAME=
      - DATABASE_PASSWORD=
      - DATABASE_SSL=false
      - DATABASE_AUTHENTICATION_DATABASE=strapi
      - HOST=localhost
    ports:
      - 1337:1337
    volumes:
      - ./healthdesk-app:/usr/src/api/healthdesk-api
      #- /usr/src/api/strapi-app/node_modules
    depends_on:
      - db
    restart: always

  db:
    image: mongo
    container_name: healthdesk-db
    environment:
      - MONGO_INITDB_DATABASE=healthdesk-db
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
    restart: always
